compass/people.py
compass/utility.py

Fixes conditions where:
- Datetime isn't returned in Compass
- Is set to 'Unknown'

Added fix for safe datetime parsing

---

compass/_scrapers/member.py
compass/_scrapers/reports.py
compass/errors.py
compass/logon.py
compass/reports.py
compass/settings.py
compass/utility.py

As it says on the tin!
Not much functionality change, but a general tidying up so that work can be done more easily in future - reports was the main bit of CI I was stuck on and never finished (and would be most useful to a lot of my other roles).
I co-erced things into the general template we've been using for Hierarchy & Members - a public interface Reports class, and an implementation level ReportsScraper. 
To note - the one real cludge I'm still not massively happy with is in `Reports.__init__` in monkeypatching the `Login._get()` method onto the `ReportsScraper._get()` method - this works, but would like a better solution. This is the second place we've needed the Auth & JK hash stuff - not sure if this will be the last, or if some effort should be made to generalise. (Note …

Reports improvements

---

compass/core/_scrapers/reports.py
compass/core/hierarchy.py
compass/core/schemas/member.py
compass/core/utility.py
tests/test_compass_core_utility.py

Standardise filesystem guards. Also adds tests

Standardised filesystem guards

---

tests/test_compass_core_schemas_hierarchy.py
tests/test_compass_core_utility.py

Schema testing

---

compass/core/_scrapers/hierarchy.py
compass/core/_scrapers/member.py
compass/core/_scrapers/reports.py
compass/core/hierarchy.py
compass/core/interface_base.py
compass/core/logon.py
compass/core/people.py
compass/core/schemas/member.py
compass/core/utility.py
environment.yml
setup.cfg

Some warnings remain, but better.

Towards type checking

---

codecov.yml
compass/core/_scrapers/hierarchy.py
compass/core/_scrapers/member.py
compass/core/_scrapers/reports.py
compass/core/hierarchy.py
compass/core/interface_base.py
compass/core/logger.py
compass/core/logon.py
compass/core/people.py
compass/core/reports.py
compass/core/schemas/member.py

✨ Add disclosures data access!

---

compass/core/_scrapers/member.py

🐛 Fix bug for where GDPR not validated

---

compass/core/_scrapers/member.py
compass/core/people.py
compass/core/schemas/member.py

✨ Add Awards!

---

compass/core/_scrapers/member.py
compass/core/schemas/member.py

Parses serialised address strings to fields.

Add address parsing

---

compass/core/logon.py
compass/core/schemas/logon.py
compass/core/settings.py

Now able to create Logon objects from pre existing compass session IDs/tokens

✨ Add Logon.from_session!

---

README.md

PR 42!
Updates README with more login examples, and the new `import compass.core as ci` incantation

📝 Update README examples

---

compass/core/people.py

🐛 Unhashable keys in People.latest_disclosure

---

compass/core/_scrapers/member.py

🐛 Fix `Ending` statuses in People.roles

---

compass/core/_scrapers/member.py

Actually fixes #52, resolves #53

🐛 Fix fix for  `Ending` statuses in People.roles`

---

compass/core/_scrapers/member.py
compass/core/people.py
compass/core/schemas/member.py
tests/test_compass_core_scrapers_member_reduce_date_list.py

Initial stab at this, not massivley happy with `_reduce_date_list`, but it takes around 30 microseconds to process a list of pairs so optimisation here isn't really needed..!
Breaking change, as `MemberRolesDict` has gone in favour of `MemberRolesCollection`

✨ Add membership_duration

---

compass/core/_scrapers/member.py
compass/core/people.py

Might fix #55 
Extend tick-box checking, as perhaps not all roles have a tick-box in the table

🐛 Bug: off-by-one in roles table

---

compass/core/schemas/member.py

Added 'Application received at HQ' as a valid disclosure status

---

compass/core/_scrapers/member.py
compass/core/people.py
compass/core/schemas/member.py

Try to decrease complexity in the main methods by adding utility functions

🎨 Refactor `ci._scrapers.member`

---

setup.cfg

2 API changes:
- `ci.schemas.people.MemberDetails.address` is now a submodel with address parts, and the original address string. Was going to remove this but not sure if the original address is still of use to you @rglss?
- Added parsing for disability/qualifications/hobbies, and added to `ci.schemas.people.MemberDetails` model.
Internal changes include a refactor of `_scrapers/member.py` - this file is still just short of 1,000 lines long, but hopefully now control flow is slightly easier to follow, as I've added a number of helper functions. Also continued to move away from xpath for performance improvements of ~100x in some cases, though this is at the parsing stage - network I/O to compass still takes up the vast majority of time. (In a recent test, 300ms network I/O, 75ms parsing -> …

🔖 RLS: v0.11.0

---

compass/core/_scrapers/hierarchy.py
compass/core/_scrapers/member.py
compass/core/hierarchy.py
compass/core/schemas/hierarchy.py
compass/core/settings.py
compass/core/util/cache_hooks.py
tests/compass/core/schemas/test_compass_core_schemas_hierarchy.py

Rewrite caching as decorators and a hook based system

🚚 Move caching to `compass-interface.util.cache`

---

compass/core/_scrapers/hierarchy.py
compass/core/hierarchy.py
compass/core/schemas/hierarchy.py
tests/compass/core/schemas/test_compass_core_schemas_hierarchy.py

Add ability to just fetch immediate children not full hierarchy. 
Also changed `Hierarchy` accessors, so breaking change

✨ Add immediate vs recurse children flag

---

README.md
compass/core/__init__.py
compass/core/logon.py

Breaking change as the return type of `ci.login` has changed!
Release will be `0.15.0`

✨ Add overarching `CompassInterface` class!

---

compass/core/__init__.py
compass/core/_scrapers/reports.py
compass/core/hierarchy.py
compass/core/logon.py
compass/core/people.py
compass/core/reports.py
tests/compass/core/test_compass_core_logon.py

This has been intended for a while, but unclear. Allows simplification of logic elsewhere.

♻️ Clarify that Logon properties are immutable

---

ci/requirements-run.txt
environment.yml
setup.cfg

[CVE-2021-29510]: https://github.com/samuelcolvin/pydantic/security/advisories/GHSA-5jqp-qgf6-3pvh

🔒️ Update `setup.cfg` pins for CVE-2021-29510

---

README.md
compass/core/hierarchy.py
compass/core/logon.py
compass/core/schemas/hierarchy.py

Thanks to @arbitrarypunter for reporting!

✨ Properly support sectional unit types!

---

compass/core/__init__.py
compass/core/_scrapers/contact.py
compass/core/_scrapers/hierarchy.py
compass/core/_scrapers/member_profile.py
compass/core/_scrapers/reports.py
compass/core/_scrapers/role_detail.py
compass/core/hierarchy.py
compass/core/logon.py
compass/core/people.py
compass/core/reports.py
compass/core/schemas/hierarchy.py
compass/core/schemas/logon.py
compass/core/schemas/member.py
compass/core/util/client.py
tests/compass/core/test_compass_core_errors.py
tests/compass/core/test_compass_core_logon.py

Declarativley expose the API -- as I've made some things private this will have to be `0.16.0`

🎨 Expose public API in `__init__.py`

---

compass/core/_scrapers/member_profile.py
compass/core/_scrapers/reports.py
compass/core/reports.py

- Unify report names and auto detect hierarchy level
- Don't write reports to disk
- Decode reports to strings
- Simplify scraper module

🎨 Reports part 3

---

compass/core/__init__.py
compass/core/_scrapers/reports.py
compass/core/reports.py
compass/core/schemas/reports.py
pyproject.toml

Two big changes
- Make the format argument take an iterable, to more closely mirror the web interface
- Get the training report working for regions (counties, districts yet to do)

✨ Reports, but part 5!
